# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.3'
      - name: Build for Linux
        run: go build -v -o packSigner .
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: packSigner-linux
          path: packSigner

  build-windows:
    runs-on: ubuntu-latest   # still use Ubuntu for cross-compilation
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.3'
      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -v -o packSigner.exe .
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: packSigner-windows-amd64
          path: packSigner.exe
